### ISSUE TITLE
YOUR_GCM_ID is  not the Project_ID

### ISSUE THREAD

**Issue by asutosh7hota** [googlecodelabs/migrate-to-progressive-web-apps#1]
First of all my project-id that was generated was not a whole numeric numeric number but had words, example : useful-art-136623(Its not a 12 digit number)

I tried it again but it didnt work. However, when I used my project number in its place, it worked.(My project number was a 12 digit number)

Kindly have a look at this and please change the documentation if you find the same issues.

**Comment by samthor** [comment]
We don't use GCM anymore.
